const episode1 = [
    { bgm: "assets/music/tema_mengelidiki.mp3", bg: "assets/images/bg/kelas_12-2_trisakti.png", speaker: "Dio", sprite: CHAR_ASSETS.dio.netral, text: "(Monolog) Pagi yang biasa di SMA Negeri Trisakti. Udara pagi masih terasa dingin, tapi suasana di kelas 12-2 sudah panas oleh gosip murahan. Aku, Dio, hanya bisa menyandarkan kepala di meja sambil mendengarkan celotehan teman-teman sekelasku." },
    { speaker: "Murid A", text: "(Berbisik dengan nada antusias) \"Eh, kalian udah denger berita terbaru belum? Soal SMA terbengkalai yang ada di Desa Wahyusakti?\"" },
    { speaker: "Murid B", text: "(Merinding) \"Oh, yang katanya angker banget itu? Denger-denger ada rombongan anak kampus yang coba bikin konten penelusuran di sana minggu lalu...\"" },
    { speaker: "Murid A", text: "\"Iya! Dan kabarnya... sampai sekarang mereka belum pulang. Nggak ada yang tahu mereka ke mana. Polisi aja masih nyari!\"" },
    { speaker: "Dio", spriteLeft: CHAR_ASSETS.dio.netral, spriteRight: CHAR_ASSETS.eriko.senyum, text: "(Monolog) Gosip horor. Selalu jadi menu sarapan favorit anak-anak di kelas ini. Aku melirik ke arah meja di sudut ruangan. Di sana, Eriko—atau yang biasa kami panggil Riko—sedang sibuk menggulir layar ponselnya." },
    { speaker: "Eriko", spriteLeft: CHAR_ASSETS.dio.netral, spriteRight: CHAR_ASSETS.eriko.senyum, text: "(Bicara sendiri dengan suara pelan) \"Desa Wahyusakti... SMA terbengkalai... Hilang tanpa jejak? Wah, ini sih gila. Engagement-nya pasti meledak kalau dibikin live streaming.\"" },
    { speaker: "Dio", spriteLeft: CHAR_ASSETS.dio.netral, spriteRight: CHAR_ASSETS.eriko.senyum, text: "(Monolog) Melihat seringai di wajah Riko, aku sudah punya firasat buruk. Otaknya pasti sedang merencanakan sesuatu yang merepotkan." },
    
    { bg: "assets/images/bg/klub_sastra_trisakti.png", speaker: "Dio", sprite: CHAR_ASSETS.dio.netral, text: "(Monolog) Ruang Klub Sastra. Markas rahasia kami. Meski namanya klub sastra, kami lebih sering menggunakan ruangan ini untuk sekadar makan siang atau numpang tidur." },
    { speaker: "Dio", spriteLeft: CHAR_ASSETS.dinda.senyum, spriteRight: CHAR_ASSETS.elisa.netral, text: "(Monolog) Dinda sedang membaca majalah, Raka membaca buku tebal, Duwi mengunyah keripik, dan Elisa sedang menyiram tanaman pot di dekat jendela." },
    { speaker: "Eriko", sprite: CHAR_ASSETS.eriko.senyum, shake: true, text: "(Napas terengah-engah, wajah bersemangat) \"GUYS! Berhenti dengan aktivitas membosankan kalian! Aku bawa berita besar!\"" },
    { speaker: "Duwi", sprite: CHAR_ASSETS.duwi.marah, shake: true, text: "(Tersedak keripik) \"Uhuk! Uhuk! Astaga, Riko! Jantungan aku! Nggak bisa buka pintu pelan-pelan, ya?!\"" },
    { speaker: "Raka", sprite: CHAR_ASSETS.raka.netral, text: "(Menutup bukunya perlahan, menatap dingin dari balik kacamata) \"Kalau ini soal rumor murahan yang beredar di kelas tadi pagi, pintu keluarnya ada di belakangmu, Rik.\"" },
    { speaker: "Eriko", sprite: CHAR_ASSETS.eriko.marah, text: "(Cemberut) \"Yah, elah, Ka. Dengerin dulu! Ini bukan rumor sembarangan. Kalian tahu kasus hilangnya anak-anak yang bikin konten di Desa Wahyusakti, kan?\"" },
    { speaker: "Dinda", sprite: CHAR_ASSETS.dinda.senyum, text: "(Menutup majalahnya, matanya berbinar penasaran) \"Aku dengar! Katanya sekolah itu dulunya ditutup paksa karena ada insiden berdarah puluhan tahun lalu, kan? Wah, misterius banget!\"" },
    { speaker: "Elisa", sprite: CHAR_ASSETS.elisa.takut, text: "(Berbalik dari jendela, memeluk pot siramannya, wajahnya cemas) \"Aku... aku tidak suka membicarakan tempat itu. Auranya terasa sangat gelap, meskipun hanya dari cerita...\"" },
    { speaker: "Dio", sprite: CHAR_ASSETS.dio.netral, text: "(Menghela napas) \"Terus? Apa hubungannya berita itu sama kita, Rik? Jangan bilang...\"" },
    { speaker: "Eriko", sprite: CHAR_ASSETS.eriko.senyum, text: "(Menggebrak meja perlahan, tersenyum lebar) \"Tepat sekali, Dio! Nanti malam, kita bakal bikin sejarah. Kita akan ekspedisi langsung ke SMA terbengkalai di Desa Wahyusakti!\"" },
    { speaker: "Duwi", sprite: CHAR_ASSETS.duwi.takut, shake: true, text: "(Berdiri panik, keripiknya tumpah) \"HAAAH?! KAU GILA?! NGGAK! AKU NGGAK MAU IKUT! Aku masih mau hidup, masih mau nikah, masih mau—\"" },
    { speaker: "Raka", sprite: CHAR_ASSETS.raka.marah, text: "(Memotong ucapan Duwi, menghela napas panjang) \"Ini tindakan bodoh, Riko. Masuk tanpa izin ke properti terbengkalai itu melanggar hukum. Belum lagi kalau bangunan itu rapuh dan runtuh.\"" },
    { speaker: "Eriko", sprite: CHAR_ASSETS.eriko.senyum, text: "\"Aduh, Raka, logika terus yang dipakai. Ini soal adrenalin! Soal pembuktian! Dan bayangkan... kalau kita berhasil rekam sesuatu yang gila, channel kita bakal viral! Dinda, kau pasti mau ikut, kan?\"" },
    { speaker: "Dinda", sprite: CHAR_ASSETS.dinda.senyum, text: "(Tersenyum menantang) \"Sejujurnya? Aku penasaran banget. Kalau cuma diam di sekolah, hidup kita terlalu membosankan. Aku ikut!\"" },
    { speaker: "Elisa", sprite: CHAR_ASSETS.elisa.takut, text: "(Menunduk, suaranya bergetar) \"Ta-tapi... bagaimana kalau cerita hilangnya orang-orang itu benar? Sesuatu di sana mungkin sedang... menunggu.\"" },
    { speaker: "Duwi", sprite: CHAR_ASSETS.duwi.takut, text: "\"Tuh kan! Elisa aja udah merinding! Udahlah, mending kita mabar game aja di warnet nanti malam!\"" },
    { speaker: "Eriko", sprite: CHAR_ASSETS.eriko.senyum, text: "(Menatap Dio, memohon) \"Dio, ayolah. Kau ketuanya di sini. Kau yang bisa menengahi. Kita cuma lihat-lihat, rekam bentar, kalau ada apa-apa kita langsung lari. Janji!\"" },
    { speaker: "Dio", sprite: CHAR_ASSETS.dio.netral, text: "(Monolog) Seperti biasa, semua keputusan akhir diserahkan padaku. Kalau aku menolak, Riko dan Dinda pasti akan nekat pergi berdua, dan itu jauh lebih berbahaya. Kalau aku setuju... aku harus memastikan kawan-kawanku selamat." },
    { speaker: "Dio", text: "Apa yang harus aku katakan?", choices: [ { text: "\"Baiklah, aku ikut. Tapi aku yang pegang kendali.\"", jump: "choice_a" }, { text: "\"Ini ide gila, tapi aku gak bisa biarin kalian pergi sendiri.\"", jump: "choice_b" } ] },
    { id: "choice_a", speaker: "Eriko", sprite: CHAR_ASSETS.eriko.senyum, text: "\"Mantap! Itulah kapten kita!\"", jump: "merge" },
    { id: "choice_b", speaker: "Raka", sprite: CHAR_ASSETS.raka.senyum, text: "\"Alasan yang rasional. Aku juga berpikiran sama, Dio.\"", jump: "merge" },
    { id: "merge", speaker: "Dio", sprite: CHAR_ASSETS.dio.netral, text: "\"Jam berapa rencanamu, Rik?\"" },
    { speaker: "Eriko", sprite: CHAR_ASSETS.eriko.senyum, text: "(Mengepalkan tangan kegirangan) \"Yes! Jam 10 malam! Kita kumpul di pertigaan dekat gerbang Desa Wahyusakti. Aku bawa kamera dan senter!\"" },
    { speaker: "Duwi", sprite: CHAR_ASSETS.duwi.takut, text: "(Lemas, merosot ke kursi) \"Matilah kita...\"" },
    { speaker: "Raka", sprite: CHAR_ASSETS.raka.netral, text: "(Merapikan kacamatanya) \"Baiklah. Aku ikut. Tapi ingat, kalau kurasa situasinya membahayakan nyawa, aku akan menarik kalian semua pulang paksa. Mengerti?\"" },
    { speaker: "Elisa", sprite: CHAR_ASSETS.elisa.takut, text: "(Mengangguk pelan) \"Kalau kalian semua pergi... aku juga ikut. Aku mungkin bisa... merasakan kalau ada bahaya yang mendekat.\"" },
    { speaker: "Dinda", sprite: CHAR_ASSETS.dinda.senyum, text: "(Melompat kegirangan) \"Asyik! Ekspedisi Klub Sastra! Jangan lupa pakai baju hangat, ya!\"" },
    { speaker: "Dio", sprite: CHAR_ASSETS.dio.netral, text: "(Monolog) Dan begitulah. Rasa penasaran mengalahkan akal sehat kami. Saat itu, kami tidak tahu bahwa keputusan yang dibuat di ruang klub siang ini, akan mengubah hidup kami... atau bahkan mengakhirinya." },
    
    { bgm: "assets/music/tema2.mp3", bg: "assets/images/bg/wahyu_halaman_sekolah.png", speaker: "Dio", sprite: CHAR_ASSETS.dio.netral, text: "(Monolog) Jam di ponselku jelas menunjukkan pukul 22:00 WIB. Tapi, begitu kami berdiri tepat di depan gerbang berkarat SMA Wahyusakti, ada yang tidak masuk akal." },
    { speaker: "Raka", sprite: CHAR_ASSETS.raka.marah, text: "(Mengernyitkan dahi, menatap langit di atas bangunan sekolah) \"Ini... tidak logis. Perhatikan langit di atas lapangan sekolah itu. Kenapa warnanya jingga kemerahan?\"" },
    { speaker: "Duwi", sprite: CHAR_ASSETS.duwi.takut, shake: true, text: "(Menggosok matanya berkali-kali) \"I-iya! Kok kayak masih jam 5 sore?! Padahal di luar gerbang ini gelap gulita! Kita pulang aja yuk, guys! Ini udah nggak beres!\"" },
    { speaker: "Eriko", sprite: CHAR_ASSETS.eriko.senyum, text: "(Menyalakan kamera, wajahnya berseri-seri) \"Gilaaa! Baru sampai gerbang udah disuguhi anomali keren begini! Ini pasti efek cahaya dari kota atau gas rawa. Ayo, kita masuk!\"" },
    { speaker: "Dio", sprite: CHAR_ASSETS.dio.netral, text: "(Monolog) Sebelum Riko melangkah maju, sesosok bayangan kecil muncul dari balik pilar gerbang." },
    { bgm: "assets/music/tema_anak_kecil.mp3", speaker: "Dio", spriteRight: CHAR_ASSETS.gadis_kecil.netral, text: "(Monolog) Seorang anak perempuan kecil pucat dengan gaun lusuh era lama, menatap mereka dengan tatapan kosong." },
    { speaker: "Anak Kecil", spriteRight: CHAR_ASSETS.gadis_kecil.netral, text: "(Suaranya datar, tanpa emosi) \"Jangan masuk... Tempat ini bukan untuk kalian. Ada ruangan gaib di dalam sana... yang masuk, tidak akan pernah keluar.\"" },
    { speaker: "Elisa", spriteLeft: CHAR_ASSETS.elisa.takut, spriteRight: CHAR_ASSETS.gadis_kecil.netral, text: "(Mundur selangkah, memegang lengan Dio) \"Di-Dio... anak itu... kakinya...\"" },
    { speaker: "Eriko", sprite: CHAR_ASSETS.eriko.senyum, text: "(Menurunkan kameranya sedikit, tertawa canggung) \"Hahaha, halo Dek. Malam-malam main di sini, rumahnya di mana? Kita cuma mau bikin video sebentar kok, habis itu pulang.\"" },
    { speaker: "Anak Kecil", spriteRight: CHAR_ASSETS.gadis_kecil.marah, text: "(Tidak mempedulikan Eriko, menatap tajam ke arah Dio) \"Apapun yang terjadi, aku sudah memperingatkan. Jangan menyesal.\"" },
    { bgm: "assets/music/tema2.mp3", speaker: "Dio", sprite: CHAR_ASSETS.dio.netral, text: "(Monolog) Aku reflek menutup mata karena debu. Namun saat kubuka mataku sedetik kemudian... gadis kecil itu sudah tidak ada. Hilang tanpa jejak di area yang terbuka lebar." },
    { speaker: "Duwi", sprite: CHAR_ASSETS.duwi.takut, shake: true, text: "(Gemetar hebat, memeluk tas ranselnya) \"Hi-hilang... Dia hilang, woy! Yakin nih kita beneran mau masuk?! Itu tadi jelas-jelas bukan manusia!\"" },
    { speaker: "Raka", sprite: CHAR_ASSETS.raka.netral, text: "(Memperbaiki letak kacamatanya, meski wajahnya sedikit tegang) \"Mungkin dia lari ke semak-semak saat kita menutup mata. Kecepatannya mengesankan, tapi... mari kita tetap waspada.\"" },
    { speaker: "Dio", spriteLeft: CHAR_ASSETS.dio.netral, spriteRight: CHAR_ASSETS.elisa.takut, text: "(Monolog) Elisa tiba-tiba memegang kepalanya, meringis kesakitan." },
    { speaker: "Elisa", sprite: CHAR_ASSETS.elisa.takut, shake: true, text: "\"Akh...\"" },
    { speaker: "Dinda", spriteLeft: CHAR_ASSETS.dinda.takut, spriteRight: CHAR_ASSETS.elisa.takut, text: "(Panik) \"Elisa? Kamu kenapa? Mukamu pucat banget!\"" },
    { speaker: "Elisa", sprite: CHAR_ASSETS.elisa.takut, text: "(Napasnya agak berat) \"Kepalaku... tiba-tiba pusing sekali. A-ada yang nggak beres di sini. Aku merasa... dari kegelapan di dalam sana, ada puluhan mata yang sedang memperhatikan kita...\"" },
    { speaker: "Eriko", sprite: CHAR_ASSETS.eriko.senyum, text: "(Menepuk bahu Elisa, tersenyum meremehkan) \"Aduh, Elisa... Kamu kebanyakan nonton film horor sih. Sugesti itu namanya. Tenang aja, ada aku dan Raka yang bakal jagain kalian!\"" },
    { speaker: "Dio", sprite: CHAR_ASSETS.dio.netral, text: "\"Tetap rapatkan barisan. Riko, jangan jauh-jauh. Kita masuk sekarang.\"" },
    
    { bgm: "assets/music/alam_gaib.mp3", bg: "assets/images/bg/wahyu_lobi.png", speaker: "Dio", sprite: CHAR_ASSETS.dio.netral, text: "(Monolog) Saat kami melangkah masuk ke lobi, ilusi sore hari di luar tadi langsung menghilang. Kegelapan pekat menyambut kami. Bau debu, kayu lapuk, dan sesuatu yang amis menguar di udara." },
    { speaker: "Elisa", sprite: CHAR_ASSETS.elisa.takut, text: "(Monolog Batin) Udaranya... pekat sekali. Berat. Seperti ada yang bernapas di leherku. Kenapa mereka tidak merasakannya? Auranya merah kehitaman... Kita tidak seharusnya ada di sini." },
    { speaker: "Dio", spriteLeft: CHAR_ASSETS.dio.netral, spriteRight: CHAR_ASSETS.elisa.takut, text: "(Monolog) Bagi kami, ini hanya bangunan tua yang seram. Tapi melihat Elisa yang terus gemetar sambil menunduk, aku tahu dia melihat hal-hal yang tidak bisa kami lihat." },
    { speaker: "Duwi", sprite: CHAR_ASSETS.duwi.takut, shake: true, text: "(Menjerit histeris) \"HWAAAAA! APA ITU?!\"" },
    { speaker: "Raka", sprite: CHAR_ASSETS.raka.marah, text: "(Menghela napas) \"Itu cuma tikus, Duwi. Tenanglah. Jangan membuat keributan yang tidak perlu.\"" },
    { bg: "assets/images/bg/wahyu_loker.png", speaker: "Elisa", sprite: CHAR_ASSETS.elisa.takut, text: "(Tiba-tiba berhenti melangkah, matanya terbelalak menatap deretan loker di ujung koridor) \"T-tunggu... Di sana... Ada wanita berdiri...\"" },
    { speaker: "Dio", sprite: CHAR_ASSETS.dio.netral, text: "Apa yang harus dilakukan?", choices: [
        { text: "Periksa area sekitar loker", jump: "quest_loker_investigate" },
        { text: "Abaikan dan tetap jalan bersama", jump: "quest_loker_ignore" }
    ]},

    { id: "quest_loker_ignore", speaker: "Raka", sprite: CHAR_ASSETS.raka.netral, text: "\"Pilihan bijak. Kita harus tetap berada di jalur utama dan tidak terpisah.\"" },
    { speaker: "Eriko", sprite: CHAR_ASSETS.eriko.ngambek, text: "\"Yaaah, padahal seru kalau diperiksa dulu. Ya sudahlah...\"", jump: "quest_loker_end" },

    { id: "quest_loker_investigate", speaker: "Dio", sprite: CHAR_ASSETS.dio.netral, text: "Aku melangkah mendekati deretan loker tua itu. Tempat mana yang harus kuperiksa?", choices: [
        { text: "Lihat samping loker", jump: "safe_choice" },
        { text: "Lihat jendela", jump: "jump_choice_1" },
        { text: "Lihat dalam loker", jump: "jump_choice_2" },
        { text: "Lihat tirai", jump: "jump_choice_3" }
    ]},

    { id: "jump_choice_1", jumpscare: true, speaker: "Dio", sprite: CHAR_ASSETS.dio.takut, shake: true, text: "(Sesuatu melompat tepat di depan wajahku!) \"HWAAA! ASTAGA!\"", jump: "quest_loker_end" },
    { id: "jump_choice_2", jumpscare: true, speaker: "Dio", sprite: CHAR_ASSETS.dio.takut, shake: true, text: "(Loker mendadak terbuka sendiri dan bayangan hitam menyambar!) \"AAARRGH!\"", jump: "quest_loker_end" },
    { id: "jump_choice_3", jumpscare: true, speaker: "Dio", sprite: CHAR_ASSETS.dio.takut, shake: true, text: "(Tirai tersingkap dan sesosok muka hancur menatapku erat!) \"HWAAA!\"", jump: "quest_loker_end" },

    { id: "safe_choice", speaker: "Dio", sprite: CHAR_ASSETS.dio.netral, text: "(Melihat dengan hati-hati ke samping loker) Tidak ada apa-apa di sini, hanya genangan air tua dan tumpukan buku lapuk. Aman." },
    { speaker: "Elisa", sprite: CHAR_ASSETS.elisa.takut, text: "(Menghela napas panjang) \"Bayangan itu... baru saja bergeser... Tapi syukurlah kamu baik-baik saja, Dio...\"", jump: "quest_loker_end" },

    { id: "quest_loker_end", bg: "assets/images/bg/wahyu_koridor.png", speaker: "Dio", sprite: CHAR_ASSETS.dio.netral, text: "(Monolog) Meski kejadian di lobi tadi cukup mengguncang mental, terutama bagi Duwi dan Dinda, Riko bersikeras agar kami terus maju. Cahaya senter kami menyapu lorong sekolah yang panjang, berdebu, dan dipenuhi sarang laba-laba. Suasananya benar-benar mencekam." },
    { speaker: "Dinda", sprite: CHAR_ASSETS.dinda.takut, text: "(Berhenti melangkah, menyilangkan kaki sambil memegangi perutnya) \"Aduh... guys, tunggu bentar.\"" },
    { speaker: "Duwi", spriteLeft: CHAR_ASSETS.dinda.takut, spriteRight: CHAR_ASSETS.duwi.marah, text: "(Menoleh) \"Kenapa lagi, Din? Jangan bilang kamu lihat hantu lagi!\"" },
    { speaker: "Dinda", sprite: CHAR_ASSETS.dinda.takut, text: "(Wajahnya memerah malu campur panik) \"Bukan! Aku... aku kebelet pipis nih. Sumpah, nggak tahan lagi dari tadi nahan takut!\"" },
    { speaker: "Eriko", sprite: CHAR_ASSETS.eriko.senyum, text: "(Tertawa pelan) \"Yaelah, Din. Timing-mu jelek banget sih. Ya udah, cari toilet gih.\"" },
    { speaker: "Dinda", spriteLeft: CHAR_ASSETS.dio.netral, spriteRight: CHAR_ASSETS.dinda.takut, text: "(Menarik ujung jaket Dio) \"Dio, temenin dong! Aku nggak berani sendirian, apalagi tadi ada kejadian di loker.\"" },
    { speaker: "Dio", sprite: CHAR_ASSETS.dio.netral, text: "(Menghela napas pasrah) \"Ya, ya, ayo. Kalian tunggu di sini sebentar, jangan ke mana-mana.\"" },
    { speaker: "Raka", sprite: CHAR_ASSETS.raka.netral, text: "\"Jangan lama-lama. Kami tunggu di persimpangan lorong ini.\"" },
    { bg: "assets/images/bg/wahyu_toilet.png", speaker: "Dio", sprite: CHAR_ASSETS.dio.netral, text: "(Monolog) Kami menemukan toilet perempuan tak jauh dari sana. Namun, ada satu hal aneh yang langsung membuatku merinding. Di saat seluruh lorong ini gelap gulita dan hanya mengandalkan cahaya senter kami... entah kenapa, area di dalam kamar mandi ini terlihat jauh lebih terang. Bukan karena lampu menyala, tapi seperti ada pendaran cahaya pucat dari ubinnya sendiri." },
    { speaker: "Dinda", sprite: CHAR_ASSETS.dinda.takut, text: "(Ragu-ragu berdiri di ambang pintu) \"Dio... kok toiletnya agak terang, ya? Dibanding ruangan lain...\"" },
    { speaker: "Dio", sprite: CHAR_ASSETS.dio.netral, text: "\"Mungkin pantulan cahaya bulan dari ventilasi. Udah, buruan masuk. Aku jaga di luar pintu.\"" },
    { speaker: "Dinda", sprite: CHAR_ASSETS.dinda.takut, text: "(Masuk perlahan ke dalam) \"Dio... jangan tinggalkan aku ya! Tunggu di situ aja!\"" },
    { speaker: "Dio", sprite: CHAR_ASSETS.dio.netral, text: "(Tersenyum iseng, menyandarkan punggung ke dinding) \"Iya, iya. Jangan lama-lama, entar kutinggal beneran lho.\"" },
    { speaker: "Dinda", sprite: CHAR_ASSETS.dinda.takut, text: "(Berteriak dari dalam) \"JANGAN DONG!\"" },
    { speaker: "Dio", sprite: CHAR_ASSETS.dio.netral, text: "(Monolog) Beberapa detik berlalu dalam keheningan. Namun tiba-tiba...\nSuara tawa wanita terdengar hihihi" },
    { speaker: "Dinda", sprite: CHAR_ASSETS.dinda.takut, text: "(Dari dalam kamar mandi, panik) \"Dio?! Kamu dengar itu?!\"" },
    { speaker: "Dio", sprite: CHAR_ASSETS.dio.netral, text: "\"Dengar apa? Udah kelar belum?\"" },
    { speaker: "Dinda", sprite: CHAR_ASSETS.dinda.takut, text: "(Monolog Batin) Aku mendengar suara tertawa tapi saat ku tanya ke dio sepertinya gak denger dia nya." },
    { speaker: "Dinda", sprite: CHAR_ASSETS.dinda.takut, text: "(Berlari keluar dengan wajah sangat palid) \"Udah! Ayo balik, cepetan!\"" },
    { bg: "assets/images/bg/wahyu_koridor.png", speaker: "Dio", sprite: CHAR_ASSETS.dio.netral, text: "(Monolog) Eriko, Raka, Duwi, dan Elisa menoleh ke arah Dio dan Dinda yang datang." },
    { speaker: "Dinda", spriteLeft: CHAR_ASSETS.dio.netral, spriteRight: CHAR_ASSETS.dinda.takut, text: "(Napasnya terengah-engah, memegang lengan Dio erat) \"Dio... kamu tadi dengar sesuatu nggak di WC?\"" },
    { speaker: "Dio", sprite: CHAR_ASSETS.dio.netral, text: "(Mencoba mencairkan suasana) \"Ya kan kamu yang di dalam kamar mandi, aku di luar. Aku mana tau ada suara apa.\"" },
    { speaker: "Dinda", spriteLeft: CHAR_ASSETS.dio.netral, spriteRight: CHAR_ASSETS.dinda.ngambek, text: "(Cemberut, memukul bahu Dio pelan) \"Ihh! Kamu malah bercanda! Aku serious, Dio!\"" },
    { speaker: "Dio", sprite: CHAR_ASSETS.dio.netral, text: "(Kembali serius) \"Enggak kok, memangnya suara apa, Din?\"" },
    { speaker: "Eriko", spriteLeft: CHAR_ASSETS.dinda.takut, spriteRight: CHAR_ASSETS.eriko.senyum, text: "(Mendekat dengan mata berbinar penasaran, menodongkan kamera) \"Wah, ada apa nih? Ada apa? Dapat fenomena apa kamu di dalam, Din?\"" },
    { speaker: "Dinda", sprite: CHAR_ASSETS.dinda.takut, text: "(Menelan ludah, suaranya bergetar) \"Pas aku lagi pipis... aku dengar kayak suara ketawa. Tapi agak samar-samar gitu... suaranya kayak suara perempuan.\"" },
    { speaker: "Duwi", sprite: CHAR_ASSETS.duwi.takut, shake: true, text: "(Melompat mundur, langsung memegang kepalanya) \"Tuh k-kan! Aduh guys, mending kita pulang aja yuk! Ini tempatnya udah nggak bener! Kita lanjutkan aja besok, kalau udah siang aja eksplorasinya!\"" },
    { speaker: "Eriko", spriteLeft: CHAR_ASSETS.duwi.takut, spriteRight: CHAR_ASSETS.eriko.marah, text: "(Mendecakkan lidah, menepuk jidat Duwi) \"Aduh, Duwi, Duwi... mana ada ekspedisi horor siang-siang bolong! Namanya juga uji nyali, ya malam lah!\"" },
    { bgm: "assets/music/tema3.mp3", speaker: "Duwi & Dinda", sprite: CHAR_ASSETS.duwi.takut, text: "\"HWAAAAA!\"" },
    { speaker: "Dio", sprite: CHAR_ASSETS.dio.netral, text: "(Monolog) Suara benda jatuh yang sangat keras dan berat tiba-tiba terdengar dari Ruang Kelas 1 yang berada tepat di sebelah kami. Semuanya langsung terdiam kaku. Napas tertahan." },
    { speaker: "Eriko", sprite: CHAR_ASSETS.eriko.netral, text: "(Wajahnya sempat pias sedetik, lalu dipaksakan tersenyum sombong) \"A-alah... paling tikus lagi loh itu. Tikus got kan gede-gede.\"" },
    { speaker: "Raka", spriteLeft: CHAR_ASSETS.eriko.netral, spriteRight: CHAR_ASSETS.raka.marah, text: "(Menatap Eriko tajam) \"Tikus tidak menjatuhkan lemari besi, Riko. Suara tadi terlalu berat. Kita butuh tempat untuk menyusun rencana ulang sebelum bergerak lebih jauh.\"" },
    { speaker: "Dio", sprite: CHAR_ASSETS.dio.netral, text: "\"Raka benar. Tetap waspada. Kita cari ruangan tertutup yang bisa dipakai buat istirahat sebentar dan berlindung.\"" },
    { speaker: "Dio", sprite: CHAR_ASSETS.dio.netral, text: "(Monolog) Kami menyusuri lorong dengan cepat dan hati-hati, hingga akhirnya menemukan perpustakaan di ujung sayap kiri. Ruangan ini tidak memiliki banyak jendela, sehingga terasa sedikit lebih tertutup dari pandangan luar." },
    { bgm: "assets/music/tema_mengelidiki.mp3", bg: "assets/images/bg/wahyu_perpus.png", speaker: "Dio", sprite: CHAR_ASSETS.dio.netral, text: "(Menyorotkan senter ke tengah ruangan) \"Baiklah, kita istirahat dulu di sini. Atur napas kalian. Kita harus bicarakan mau ekspedisi dari mana dulu, dan membagi rute evakuasi kalau terjadi apa-apa.\"" },
    { speaker: "Elisa", spriteLeft: CHAR_ASSETS.dio.netral, spriteRight: CHAR_ASSETS.elisa.senyum, text: "(Mengangguk pelan kepada Dio, setuju) \"Iya, aku setuju.\"" },
    { speaker: "Elisa", sprite: CHAR_ASSETS.elisa.netral, text: "(Monolog Batin) Baguslah kita masuk ke sini... Dari semua tempat di sekolah ini yang dipenuhi aura merah mengerikan, sepertinya ruangan ini satu-satunya yang paling aman. Entah kenapa, makhluk-makhluk itu tidak berani mendekati perpustakaan ini.", endEpisode: true }
];
